spring.application.name=MailScheduler

spring.datasource.url=jdbc:h2:file:./maildb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.generate-ddl=true

spring.h2.console.enabled=true

spring.mail.host=smtp.gmail.com
spring.mail.username=mail111sender@gmail.com
spring.mail.password=
spring.mail.port=587
spring.mail.protocol=smtp